---
abstract: 'Simple IP address access control middleware'
author:
  - 'Rintaro Ishizaki <rintaro@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-IPAddressFilter
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Net::IP::AddrRanges: 0
  Plack: 0
resources:
  homepage: http://github.com/rintaro/Plack-Middleware-IPAddressFilter/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rintaro/Plack-Middleware-IPAddressFilter.git
version: 0.02
